shared at : `shorturl.at/mntO9`

In [ ]:
import numpy as np #creating an alias for numpy

print(np.__version__)

1.18.5


## Task 1

In [ ]:
num1 = np.arange(8)
num2 = np.arange(1.2, 2.2, 0.2)
names= np.array(['Mary', 'John', 'Peter', 'Christine'], dtype='object')
dates= np.arange(start ='2000-02-01', stop ='2000-03-01', dtype='datetime64[D]' )
random_no = np.random.randint(10)
random_no = np.random.randint(low=100,high=200,size =20)
evenly_spaced = np.linspace(start= 5,stop = 10,num = 50)
names
dates
random_no
evenly_spaced

array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [ ]:
num3 = np.arange(1,9)
num3 = num3.reshape(2,4)
num3
num4 = np.arange(1.5,10.5)
num4 = num4.reshape(3,3)
num4
a = np.arange(1.6,1.9,0.1)
b = np.arange(2.5,10,2.5)
c = np.arange(20,80,20)
num5 = np.array((a,b,c))
num5

num6 = np.zeros((3,4))
num6

num7 = np.ones((5,5))
num7

num8 = np.full(shape=(4,3),fill_value=10.5)
num8

num9 = np.eye(4)
num9

num10 = np.random.randint(low = 1, high = 6, size=(4,8))
num10

array([[5, 4, 5, 2, 1, 2, 2, 2],
       [4, 5, 3, 4, 2, 2, 1, 1],
       [1, 2, 4, 1, 2, 1, 4, 1],
       [2, 2, 5, 4, 5, 5, 5, 5]])

In [ ]:
a = np.array([1.55,1.73,1.9,1.72,1.66,1.8])

b = np.array([('red', 'green', 'yellow', 'blue'),(True,False, False, True), 
              ('2017-10-01', '2017-11-11', '2017-12-23', '2018-03-31')])
c = np.array([[(10,9,8,7),(6,5,4,3)], [(1,2,3,4),(5,6,7,8)]])

# Data loaded from the textfile data1.txt
d = np.loadtxt("/content/drive/MyDrive/PDS/data1.txt", delimiter = ",",dtype='object')


In [ ]:
#Task 1
#Shape
print("shape")
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

#No of rows
print("len")
print(len(a))
print(len(b))
print(len(c))
print(len(d))

#ndim
print("ndim")
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

#size
print("size")
print(a.size)
print(b.size)
print(c.size)
print(d.size)

shape
(6,)
(3, 4)
(2, 2, 4)
(4, 4)
len
6
3
2
4
ndim
1
2
3
2
size
6
12
16
16


In [ ]:
b

array([['red', 'green', 'yellow', 'blue'],
       ['True', 'False', 'False', 'True'],
       ['2017-10-01', '2017-11-11', '2017-12-23', '2018-03-31']],
      dtype='<U10')

In [ ]:
print("Array a")
print(type(a))
print(a.dtype) #only if type is ndarray

print("Array b")
print(type(b))
print(b.dtype) #only if type is ndarray

print("Array c")
print(type(c))
print(c.dtype) #only if type is ndarray

print("Array d")
print(type(d))
print(d.dtype) #only if type is ndarray

Array a
<class 'numpy.ndarray'>
float64
Array b
<class 'numpy.ndarray'>
<U10
Array c
<class 'numpy.ndarray'>
int64
Array d
<class 'numpy.ndarray'>
object


In [ ]:
a = np.array([ ['Mary', 'John','Bob'], 
               ['Zoe', 'Chris','Ann'],
               ['Leon', 'Kathy','Sam']])
a.flatten()

array(['Mary', 'John', 'Bob', 'Zoe', 'Chris', 'Ann', 'Leon', 'Kathy',
       'Sam'], dtype='<U5')

In [ ]:
# (a)	Write Python code to convert the following 1-D array a into a 3x5 multi-dimensional array

a = np.arange(15,30)
a = a.reshape(3,5)
print(a)
# (b)	Convert the following 2x6 array b into a 3x4 array

b = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])
b = b.reshape(3,4)
print(b)


[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# transpose
a = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])
a.transpose()
# a.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [ ]:
a = np.array([ 1,2,3,4,5,6])
b = np.copy(a)
print(b is a)
a[1] = 10
print(b)

False
[1 2 3 4 5 6]


In [ ]:
b = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])
b.reshape(3,4)
print(b)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
a = np.arange(1,100,1)
b = np.array([[1,2,3,4], [100,200,300,400],  [5,6,7,8],  [9,10,11,12] ])


print(a[3])
print(type(a[3]))
print(b[3])
print(type(b[3]))

print(b[1:3])

print(b[:,-1])

print(b[1,[0,-1]])

print(b[2:,1:])

print(a[10:20:2])

print(a[::-1])

4
<class 'numpy.int64'>
[ 9 10 11 12]
<class 'numpy.ndarray'>
[[100 200 300 400]
 [  5   6   7   8]]
[  4 400   8  12]
[100 400]
[[ 6  7  8]
 [10 11 12]]
[11 13 15 17 19]
[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1]


In [ ]:
b = np.arange(9.).reshape(3, 3)
print(b)
b5 = np.where( b > 5 )  #boolean mask
print(b5)

# print(b[b5]) #applying mask to the numpy array

print("*** Values of where the elements are, and their rows/columns ***")
for i in range(len(b5[0])):
  row = b5[0][i]
  col = b5[1][i]
  print("Value: {} in row {}, column {}".format(b[row][col],row,col))


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
(array([2, 2, 2]), array([0, 1, 2]))
*** Values of where the elements are, and their rows/columns ***
Value: 6.0 in row 2, column 0
Value: 7.0 in row 2, column 1
Value: 8.0 in row 2, column 2


In [ ]:
a = np.arange(100,200,1).reshape(20,5) 
b = np.arange(1,2000,20).reshape(10,10) 
c = np.array([ [1,2,3], [4,5,6]])
print(a)
print(b)
print(c)

[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]
 [125 126 127 128 129]
 [130 131 132 133 134]
 [135 136 137 138 139]
 [140 141 142 143 144]
 [145 146 147 148 149]
 [150 151 152 153 154]
 [155 156 157 158 159]
 [160 161 162 163 164]
 [165 166 167 168 169]
 [170 171 172 173 174]
 [175 176 177 178 179]
 [180 181 182 183 184]
 [185 186 187 188 189]
 [190 191 192 193 194]
 [195 196 197 198 199]]
[[   1   21   41   61   81  101  121  141  161  181]
 [ 201  221  241  261  281  301  321  341  361  381]
 [ 401  421  441  461  481  501  521  541  561  581]
 [ 601  621  641  661  681  701  721  741  761  781]
 [ 801  821  841  861  881  901  921  941  961  981]
 [1001 1021 1041 1061 1081 1101 1121 1141 1161 1181]
 [1201 1221 1241 1261 1281 1301 1321 1341 1361 1381]
 [1401 1421 1441 1461 1481 1501 1521 1541 1561 1581]
 [1601 1621 1641 1661 1681 1701 1721 1741 1761 1781]
 [1801 1821 1841 1861 1881 1901 1921 1941 1961 1981]]
[[1 2 3]

In [ ]:
print(a+b)

ValueError: ignored

In [ ]:
a2 = np.random.randint(0,100,(20,5))
print(a2)
print(a+a2)

[[46 39 59 20 28]
 [72 31 65 30  3]
 [45 59 71 10 19]
 [51 96 57 35 92]
 [58 32 37  6  7]
 [33 37 22 16  2]
 [47  9 73 66  6]
 [ 8 41 99 75 53]
 [70 51 96 93 82]
 [58 94 36 45 33]
 [19 23  6 74 77]
 [60 40 29 82 22]
 [40 51 89 55 69]
 [91 55  5 59 70]
 [40 35 79 77 32]
 [84 11 65 16 91]
 [57 40 13 62 13]
 [64 42  1 67 19]
 [ 2 72 57 70 60]
 [14 54 33 70 42]]
[[146 140 161 123 132]
 [177 137 172 138 112]
 [155 170 183 123 133]
 [166 212 174 153 211]
 [178 153 159 129 131]
 [158 163 149 144 131]
 [177 140 205 199 140]
 [143 177 236 213 192]
 [210 192 238 236 226]
 [203 240 183 193 182]
 [169 174 158 227 231]
 [215 196 186 240 181]
 [200 212 251 218 233]
 [256 221 172 227 239]
 [210 206 251 250 206]
 [259 187 242 194 270]
 [237 221 195 245 197]
 [249 228 188 255 208]
 [192 263 249 263 254]
 [209 250 230 268 241]]


In [ ]:
b = np.arange(1,2000,20).reshape(10,10) 
c = np.array([ [1,2,3], [4,5,6]])
print(c.shape)
b2 = b[0:2,0:3]
print(b2.shape)
b2 + c

(2, 3)
(2, 3)


array([[  2,  23,  44],
       [205, 226, 247]])

In [ ]:
a = np.arange(100,200,1).reshape(20,5) 
c = np.array([ [1,2,3], [4,5,6]])

a2 = a[a%2==0]
a2 = a2[0:6].reshape(2,3)

a2*c

a2/(c*10)

array([[10.        ,  5.1       ,  3.46666667],
       [ 2.65      ,  2.16      ,  1.83333333]])

In [ ]:
a = np.arange(10, 50, 0.5)
b = np.arange(10, 20, 0.1)

print(a)
print(b)

print("SD of a : {:.2f}".format(np.std(a)))
print("SD of b : {:.2f}".format(np.std(b)))

print("Var of a : {:.2f}".format(np.var(a)))
print("Var of b : {:.2f}".format(np.var(b)))

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5
 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5 30.  30.5
 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5 36.  36.5 37.  37.5
 38.  38.5 39.  39.5 40.  40.5 41.  41.5 42.  42.5 43.  43.5 44.  44.5
 45.  45.5 46.  46.5 47.  47.5 48.  48.5 49.  49.5]
[10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1 11.2 11.3
 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5 12.6 12.7
 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9 14.  14.1
 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3 15.4 15.5
 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7 16.8 16.9
 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1 18.2 18.3
 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5 19.6 19.7
 19.8 19.9]
SD of a : 11.55
SD of b : 2.89
Var of a : 133.31
Var of b : 8.33


In [ ]:
a = np.random.randint(1,1000,(3,4))
print(a)
print(a.max())
print(a.min())

indices = np.where(a==a.max())
print(str(indices[0] ) + "," + str(indices[1]))

[[921 329  65 556]
 [134 818 714 770]
 [112 837 209 955]]
955
65
[2],[3]


In [ ]:
a = np.arange(1,21).reshape(4,5)
print(a)


print(np.cumsum(a,axis = 0))
print(np.cumsum(a,axis = 1))

print(np.cumproduct(a,axis = 0))
print(np.cumproduct(a,axis = 1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 7  9 11 13 15]
 [18 21 24 27 30]
 [34 38 42 46 50]]
[[ 1  3  6 10 15]
 [ 6 13 21 30 40]
 [11 23 36 50 65]
 [16 33 51 70 90]]
[[    1     2     3     4     5]
 [    6    14    24    36    50]
 [   66   168   312   504   750]
 [ 1056  2856  5616  9576 15000]]
[[      1       2       6      24     120]
 [      6      42     336    3024   30240]
 [     11     132    1716   24024  360360]
 [     16     272    4896   93024 1860480]]


In [ ]:
import numpy as np

### Read the csv file with the loadtxt() function
fname = "/content/drive/MyDrive/PDS/singapore-residents-by-ethnic-group-and-sex-end-june-annual.csv"
data = np.loadtxt(fname, skiprows=1,dtype=[('year','i8'),('level_1','U50'), ('value','i8')],delimiter=",")

### Print out total rows of data in the file
print("There are altogether " + str(len(data))   + " rows of data in the file " + fname )
print()

### Print out the number of years of data captured
data_years = data['year']  # Just extract the year column
years = np.unique(data_years)   # Get the unique values in this column
print("There are " + str(len(years)) + 
      "years of data captured from " + 
      str(years[0]) + " to " + str(years[len(years)-1]))
print()

### Extract only the rows with “Total Residents" in the “level_1” column
keyword = 'Total Residents'
column_to_search = data[:]['level_1']
out = [i for i, v in enumerate(column_to_search) if keyword in v]
data_totalresidents = data[out]

### Print out the year which has the highest total number of residents
max = data_totalresidents['value'].max()
argmax = data_totalresidents['value'].argmax()
print("Year with the highest total number of residents: " + str(data_totalresidents[argmax]['year']))
print("Population Count: " + str(max))
print()

### Print out the year which has the lowest total number of residents
min = data_totalresidents['value'].min()
argmin = data_totalresidents['value'].argmin()

print("Year with the lowest total number of residents: " + 
      str(data_totalresidents[argmin]['year']))
print("Population Count: " + str(min))

print()



There are altogether 855 rows of data in the file /content/drive/MyDrive/PDS/singapore-residents-by-ethnic-group-and-sex-end-june-annual.csv

There are 57years of data captured from 1960 to 2016

Year with the highest total number of residents: 2016
Population Count: 3933559

Year with the lowest total number of residents: 1960
Population Count: 1646400

